GmailClient/Controllers/HomeController.cs
using System.Web.Mvc;

namespace GmailClient.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

    }
}

GmailClient/Controllers/MailController.cs
using System;
using System.Net;
using System.Web.Mvc;
using GmailClient.Models;
using GmailClient.Transport;

namespace GmailClient.Controllers
{
    /// <summary>
    /// Mail MVC controller
    /// </summary>
    [Authorize]
    public class MailController : Controller
    {
        private readonly IMailSender _sender;

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="sender">Mail sender implementation</param>
        public MailController(IMailSender sender)
        {
            if (sender == null)
                throw new ArgumentNullException("sender");
            _sender = sender;
        }

        // GET: Mail
        public ActionResult Index(string folder = "INBOX")
        {
            return View(new MailModel() { Folder = folder });
        }

        [ChildActionOnly]
        public ActionResult Compose()
        {
            return PartialView(new ComposeMailModel());
        }

        public ActionResult Send(ComposeMailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _sender.SendMail(model.To, model.Subject, model.Message);
                    return Content("Your mail was submitted successfully.");
                }
                catch (Exception ex)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Content("There was an error submitting the mail, please try again later.");
                }
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Content("Not valid data.");
            }
        }
    }
}

GmailClient/Controllers/SettingsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using GmailClient.Data;
using GmailClient.Model;
using GmailClient.Models;

namespace GmailClient.Controllers
{
    /// <summary>
    /// Settings MVC contoller (mail account settings)
    /// </summary>
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly IRepository<Account> _accountRepository;

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="accountRepository">Accounts repository implementation</param>
        public SettingsController(IRepository<Account> accountRepository)
        {
            _accountRepository = accountRepository;
        }

        /// <summary>
        /// Index action
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            AccountSettingsModel model = new AccountSettingsModel();

            Account account = _accountRepository.GetAll().FirstOrDefault();
            if (account != null)
            {
                model.Name = account.Name;
                model.Email = account.Email;
                model.Password = account.Password; // It's just example, not using encryption
            }

            return View(model);
        }

        /// <summary>
        /// Save settings action
        /// </summary>
        /// <param name="model">Account settings</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(AccountSettingsModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Account account = _accountRepository.GetAll().FirstOrDefault();
            if (account == null)
            {
                account = new Account()
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name,
                    Email = model.Email,
                    Password = model.Password
                };
                _accountRepository.Create(account);
            }
            else
            {
                account.Name = model.Name;
                account.Email = model.Email;
                account.Password = model.Password;
                _accountRepository.Update(account);
            }

            return View(model);
        }
    }
}

GmailClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>GmailClient</h1>
    <p class="lead">WEB mail client for Gmail, using the Gmail IMAP/SMTP access.</p>
    @*<p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            You have to configure google account for IMAP access.
        </p>
        <p><a class="btn btn-default" href="https://support.google.com/mail/troubleshooter/1668960?hl=en#ts=1665018" target="_blank">Enable IMAP &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Security</h2>
        <p>First you have to register and log in.</p>
        <p><a class="btn btn-default" href="@Url.Action("Register", "Account")">Register &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Gmail account</h2>
        <p>Register your Gmail account with Google id and password (single account).</p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Settings")">Settings &raquo;</a></p>
    </div>
</div>

GmailClient/Views/Home/Mail.cshtml
@{
    ViewBag.Title = "Mail";
}

<h2>Mail</h2>

<div class="row">
    <div class="col-md-3" role="complementary">
        @*Folders*@
        <div id="scanfolders">Scanning folders...</div>
        <nav>
            <ul class="nav" id="folders">
                @*<li role="presentation" class="active"><a href="#">1</a></li>*@
            </ul>
        </nav>
    </div>

    <div class="col-md-9" role="main">
        @*Messages*@
        <table id="messages" class="table table-striped">
            <thead>
            <th>Sender</th>
            <th>Subject</th>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        //Fetch folders
        $(document).ready(function () {
            $.getJSON("/api/folders", LoadFolders);
        });

        function LoadFolders(data) {
            $("#scanfolders").html("");
            $("#ulnav").html("");
            $.each(data, function (key, val) {
                $("#folders").append("<li role=\"presentation\"><a href='#' onclick='OpenFolder(\"" + val.Name + "\")'><i class=\"fa fa-folder\"></i> " + val.Name + "</a></li>");
            });
        }

        function OpenFolder(folder) {
            $.getJSON("/api/messages", "folder=" + folder, LoadMessages);
        }

        function LoadMessages(data) {
            $("#messages").find("tr:gt(0)").remove();
            $.each(data, function (key, val) {
                var tableRow = '<tr>' +
                                '<td>' + val.FromDisplayName + '</td>' +
                                '<td>' + val.Subject + '</td>' +
                                '</tr>';
                $('#messages').append(tableRow);
            });
        }
    </script>
}