GmailClient/Controllers/MailController.cs
using System;
using System.Net;
using System.Web.Mvc;
using GmailClient.Models;
using GmailClient.Transport;

namespace GmailClient.Controllers
{
    /// <summary>
    /// Mail MVC controller
    /// </summary>
    [Authorize]
    public class MailController : Controller
    {
        private readonly IMailSender _sender;

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="sender">Mail sender implementation</param>
        public MailController(IMailSender sender)
        {
            if (sender == null)
                throw new ArgumentNullException("sender");
            _sender = sender;
        }

        // GET: Mail
        public ActionResult Index(string folder = "INBOX")
        {
            return View(new MailModel() { Folder = folder });
        }

        [ChildActionOnly]
        public ActionResult Compose()
        {
            return PartialView(new ComposeMailModel());
        }

        public ActionResult Send(ComposeMailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _sender.SendMail(model.To, model.Subject, model.Message);
                    return Content("Your mail was submitted successfully.");
                }
                catch (Exception ex)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Content("There was an error submitting the mail, please try again later.");
                }
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Content("Not valid data.");
            }
        }
    }
}

GmailClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="@Url.Content("~/Content/font-awesome.min.css")" />
    @RenderSection("head", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Logo here", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Compose", "Compose", "Mail")</li>*@
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Mail", "Index", "Mail")</li>
                    <li>@Html.ActionLink("Settings", "Index", "Settings")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>